### ISSUE TITLE
A deleted character does not have a name on PvP Stats

### ISSUE THREAD

**Issue by Contrubius** [FrancescoBorzi/PvPstats#16]
An Undead Priest's name does not have his name appear on PvPStats, presumably because his character has been deleted.

PvPStats BG link: https://chromiecraft.com/apps/pvpstats/battleground.php?id=51559

**Comment by Helias** [comment]
Thanks for this report, we will fix it

**Comment by Helias** [comment]
fixed by https://github.com/FrancescoBorzi/PvPstats/commit/045034e0dc0a3bc5573e8e74950f328d62fbbf0f
