### ISSUE TITLE
CMangos Error

### ISSUE THREAD

**Issue by Rog360** [FrancescoBorzi/PvPstats#2]
After config change this is what it displays in Firefox. Maybe tables names changed or because my pvpstats tables are empty. Not sure why I get this message... :(

     Error querying: SELECT COUNT(*) FROM pvpstats_battlegrounds WHERE winner_faction = 1 AND DATE(date) = DATE(NOW()) UNION SELECT COUNT(*) FROM pvpstats_battlegrounds WHERE winner_faction = 0 AND DATE(date) = DATE(NOW()) ;

Thanks for your work... :)

**Comment by dagochen** [comment]
'winner_faction' needs to be replaced with 'winner_team' which fixes this issue.

**Comment by Rog360** [comment]
Thanks! I'll try asap and post back if any other issues... :)

**Comment by Rog360** [comment]
@dagochen @ShinDarth After fix above I get this error

     SELECT character_guid, count(character_guid) AS count, characters.name as character_name FROM pvpstats_players INNER JOIN pvpstats_battlegrounds ON pvpstats_players.battleground_id = pvpstats_battlegrounds.id INNER JOIN characters ON pvpstats_players.character_guid = characters.guid WHERE characters.deleteDate IS NULL AND pvpstats_players.winner = 1 AND DATE(date) = DATE(NOW()) GROUP BY character_guid ORDER BY count(character_guid) DESC LIMIT 0,20

What about pvpstats_players.winner? There is no winner column in pvpstats_players... :)

**Comment by dagochen** [comment]
cant see any error message there
