### ISSUE TITLE
[Update] For Stats

### ISSUE THREAD

**Issue by ghost** [FrancescoBorzi/PvPstats#5]
project can updated to this items?

top player Achievements
top killers
top arena points
top honor points
top arena teams
top player golds
top player duel / winers
top player play time
top player by item level gear scoure /gs

**Comment by Helias** [comment]
For top player Achiemvements and achievements stuff you can use [TC-PvEstats](https://github.com/Helias/TC-PvEstats)

**Comment by ghost** [comment]
thankyou and nice! but I need the full page for this items

top guilds
top player Achievements
top killers
top arena points
top honor points
top arena teams
top player golds
top player duel / winers
top player play time
top player by item level gear scoure /gs

can you upgrade project? please!

No one has ever done!
trinitycore and azerothcore 3.3.5

**Comment by FrancescoBorzi** [comment]
@WarCrafte thanks for your suggestion, it's a good idea but that would better be a new app rather than the PvPstats, so I close the issue here. I think a better place to post it would be [the forum](https://github.com/azerothcore/forum)

**Comment by ghost** [comment]
ok, thank you, pro dev :)

I follow you :heart:
