### ISSUE TITLE
[Realm] Multiple

### ISSUE THREAD

**Issue by ghost** [FrancescoBorzi/PvPstats#6]
Hi

Pvpstats is just for A realm or Multiple realm ?!
And how to change port mysql!? not found in the cfg!

**Comment by FrancescoBorzi** [comment]
hi @WarCrafte please use github only for bug reports, for support requests please use stackoverflow:

https://www.azerothcore.org/wiki/How-to-ask-for-help

**Comment by ghost** [comment]
@FrancescoBorzi 

Hi dear, can u updated PvPstats for Multiple realms?
or no? this is just for A realm?!

**Comment by FrancescoBorzi** [comment]
@WarCrafte it is only for one realm, just put one instance of the PvPstats per every realm you have. For example:

`www.server.com/realm1/PvPstats`
`www.server.com/realm2/PvPstats`

**Comment by FrancescoBorzi** [comment]
@WarCrafte also for the port, in your `config.php` change:

```
$db = new mysqli("localhost","root","password","characters");
```

with:

```
$db = new mysqli("localhost","root","password","characters", 3306);
```

and replace `3306` with the port that you want.

Please let me know if it works.

**Comment by ghost** [comment]
page is come online but informations not found!

![Untitled](https://user-images.githubusercontent.com/52248427/60390127-b451ee00-9ae4-11e9-94cc-07ea59f8bcf0.png)

**Comment by FrancescoBorzi** [comment]
@WarCrafte are you sure the DB is accessible via that port? Are you getting any php error?

**Comment by ghost** [comment]
yes DB is accessible ,tested by armory webs and register pages  connects is workd and active!

i changed to debug=1 but not log erros and just informations not found.

last AZ  / changed on cfg

Battleground.StoreStatistics.Enable = 1

**Comment by FrancescoBorzi** [comment]
@WarCrafte if you use port `3306` does it work?

**Comment by ghost** [comment]
Yes Connect Error (2002) Connection refused.

**Comment by FrancescoBorzi** [comment]
@WarCrafte can you please contact me on Discord? let's discuss it there

**Comment by ghost** [comment]
I have to go, but be back soon and contact to you on Discord.

THANK YOU , DEAR

**Comment by ghost** [comment]
@FrancescoBorzi 

I think the problem is because, The site is separate from the server!
Web is on host and server is on vps !

So it can not be connected $db = ?

**Comment by FrancescoBorzi** [comment]
@WarCrafte that's another problem then, let's not discuss it here since it's not a bug of PvPstats

**Comment by ghost** [comment]
@FrancescoBorzi  
Sry dear, but i will to full tested ! move pvpstats on the vps and full worked.

But in the host pvpstats can't full connect to vps ! host => vps  '2x connect ip"

ithink, db mysql cod is bug and need to record = "";

$active_group = "cms";
$active_record = TRUE;

$db = new mysqli("localhost","root","password","characters", 3306);

or more tests i will to install armory for fusioncms on the host and full worked connects to databases show all characters and informations
