### ISSUE TITLE
[TOPS Pvp & Pve] Azerothcore and TrinityCore

### ISSUE THREAD

**Issue by ghost** [FrancescoBorzi/PvPstats#8]
Hi @FrancescoBorzi  & @Helias
Please creat new project and help to update(tops pvp/pve) web.
I think it's very good and very popular!

INFORMATIONS:
The project web tops pvp and pve is for azerothcore and trinitycore last,rev 3.3.5

<b2> Ready items: (worked) </b2>
top player Achievements
top killers
top arena points
top honor points
top arena teams
top player play time

----------------------------------

<b2>Need items: (upgrade) </b2>
top guilds = is ready but don't work listed to ranked!
top player by item level gear scoure /gs  = not found, need to added
top player duel / winers = not found, need to added
top player golds = not found, need to added

-----------------------

**Comment by FrancescoBorzi** [comment]
As previously suggested, please use the [forum](https://github.com/azerothcore/forum) for such suggestions. Here it's only for PvPstats bug reports.

**Comment by WarCrafte** [comment]
@FrancescoBorzi ok dear send.

:disappointed:  
Please this web page tops so good, but need to dev for fixd..
pvp and pve
