### ISSUE TITLE
[Bug] slow page loading ..

### ISSUE THREAD

**Issue by warcrafte** [FrancescoBorzi/PvPstats#9]
Hi
needed to fixed slow page loadings!

**Comment by FrancescoBorzi** [comment]
@warcrafte I don't know what the "slow page loading" issue is for you, however it doesn't depend on the app itself but on your server.

Other setups of it don't suffer this issue: http://shinworld.altervista.org/PvPstats/

Remember to enable **latest version of PHP**, don't use an old one.
